import numpy as np
import pandas as pd
from hopp.utilities import load_yaml
import yaml
from hopp.simulation.technologies.sites import SiteInfo
import os 
# from geopy.geocoders import Nominatim
from pathlib import Path

from dotenv import load_dotenv
from hopp.utilities.keys import set_developer_nrel_gov_key, set_developer_nrel_gov_email

# Set API key
load_dotenv()
NREL_API_KEY = os.getenv("NREL_API_KEY")
NREL_API_EMAIL = os.getenv("NREL_API_EMAIL")
set_developer_nrel_gov_key(NREL_API_KEY)  # Set this key manually here if you are not setting it using the .env
set_developer_nrel_gov_email(NREL_API_EMAIL)

# Define a custom loader to ignore unknown YAML tags or objects
class CombinedLoader(yaml.SafeLoader):
    pass
def construct_python_tuple(self, node):
    return tuple(self.construct_sequence(node))
def ignore_unknown(self, node):
    return None  # Ignore and return None for any unknown object
def ignore_unknown_tags(self, tag_suffix, node):
    return None  # Ignore and return None for any unknown object

# Add the handler to the loader
CombinedLoader.add_constructor(None, ignore_unknown)

CombinedLoader.add_constructor(
    u'tag:yaml.org,2002:python/tuple',
    construct_python_tuple)

CombinedLoader.add_multi_constructor('tag:yaml.org,2002:python/object', ignore_unknown_tags)
CombinedLoader.add_multi_constructor('!python/object:', ignore_unknown_tags)
CombinedLoader.add_multi_constructor('!', ignore_unknown)
# Register a constructor to catch all python object apply tags (like NumPy)
CombinedLoader.add_multi_constructor('tag:yaml.org,2002:python/object/apply', ignore_unknown_tags)



def get_filename_from_partial_name(directory: str, search_string: str):
    """This function finds and returns the first filepath in the 
    given directory that contains the given search string. This function
    was generated by ChatGPT 20240902 and edited by Jared Thomas

    Args:
        directory (str): path to directory to search
        search_string (str): string to use to find the desired filename

    Returns:
        str: relative path to file
    """
    # List all files in the given directory
    for filename in os.listdir(directory):
        # Check if the search_string is in the filename
        if search_string in filename:
            # Construct the full path to the file
            file_path = os.path.join(directory, filename)
            # Return the path of the found file
            return file_path
    
    return False

def comparison_table(designs_to_compare=["01", "02", "03", "04", "05"]):
    ref_sys_path = "../reference_systems/"
    plant_files_path = "greenHEART/input-files/plant/"
    output_files_path = "greenHEART/output/data/"

    latlon_format = "{:.4f}".format

    # get all reference design names
    reference_design_names = os.listdir(ref_sys_path)

    # define region/area
    regions = {"01": "", "02": "", "03": "Gulf Coast", "04": "New York Bight", "05": ""}
    products = {"01": "Steel", "02": "Ammonia", "03": "Hydrogen", "04": "Hydrogen", "05": "Hydrogen"}
    foundation_type = {"01": "", "02": "", "03": "Fixed", "04": "Fixed", "05": "Floating"}
    storage_keys = {"lined_rock_cavern": "Rock cavern", "salt_cavern": "Salt cavern", "none": "None", "pipe": "Underground pipes", "turbine": "In-turbine", "pressure_vessel": "Pressure vessel"}
    states = {"01": "Minnesota", "02": "Texas", "03": "Texas", "04": "New Jersey", "05": "California"}

    qoi_dictionary_list_general = []
    qoi_dictionary_list_wind = []
    qoi_dictionary_list_pv = []
    qoi_dictionary_list_battery = []
    qoi_dictionary_list_pem = []
    qoi_dictionary_list_h2_storage = []
    qoi_dictionary_list_h2_steel = []
    qoi_dictionary_list_h2_ammonia = []

    # loop over designs
    for design in designs_to_compare:
        # get full design name
        design_name = [s for s in reference_design_names if design in s][0]
        print(f"Design: {design_name}")

        # load input files
        greenheart_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "greenheart"))
        print("    GreenHEART input loaded")
        hopp_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "hopp"))
        print("    HOPP input loaded")
        if get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "orbit"):
            orbit_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "orbit"), loader=CombinedLoader)
            print("    ORBIT input loaded")
        else:
            orbit_input = False
            print("    ORBIT input skipped")
        
        ghout_path = get_filename_from_partial_name(ref_sys_path+design_name+"/"+output_files_path, "output.yaml")
        greenheart_output = load_yaml(ghout_path)
        
        print("    GreenHEART output loaded")

        # create site object
        solar_filename = hopp_input["site"]["solar_resource_file"].split("/")[-1]
        wind_filename = hopp_input["site"]["wind_resource_file"].split("/")[-1]
        resource_path = Path(ref_sys_path, design_name, "greenHEART/input-files/weather/")
        full_solar_file_path = Path(resource_path, "solar", solar_filename).absolute()
        full_wind_file_path = Path(resource_path, "wind", wind_filename).absolute()
        site = SiteInfo(data=hopp_input["site"]["data"], solar_resource_file=full_solar_file_path, wind_resource_file=full_wind_file_path)

        # get lat lon
        lat = hopp_input["site"]["data"]["lat"]
        lon = hopp_input["site"]["data"]["lon"]

        # preliminary calculations
        num_turbines = hopp_input["technologies"]["wind"]["num_turbines"]
        turbine_rating_kw = hopp_input["technologies"]["wind"]["turbine_rating_kw"]
        pv_capacity_mw = hopp_input["technologies"]["pv"]["system_capacity_kw"]*1E-3
        wind_capacity_mw = num_turbines*turbine_rating_kw*1E-3

        # get QOIs
        qoi_general = {}
        qoi_general["ID"] = design
        qoi_general["State"] = states[design]
        qoi_general["Area"] = regions[design]
        qoi_general["Product"] = products[design]
        qoi_general["Total generation rating (MW)"] = wind_capacity_mw + pv_capacity_mw
        
        onshorewind = (greenheart_input["plant_design"][f"scenario{int(design)}"]["wind_location"].capitalize() == "Onshore")
        if onshorewind:
            qoi_general["Onshore latitude"] = str(latlon_format(float(lat)))
            qoi_general["Onshore longitude"] = str(latlon_format(float(lon)))
        else:
            qoi_general["Onshore latitude"] = str(latlon_format(float(solar_filename.split("_")[0])))
            qoi_general["Onshore longitude"] = str(latlon_format(float(solar_filename.split("_")[1])))
        if not onshorewind:
            qoi_general["Offshore latitude"] = str(latlon_format(float(lat)))
            qoi_general["Offshore longitude"] = str(latlon_format(float(lon)))
        else:
            qoi_general["Offshore latitude"] = " "
            qoi_general["Offshore longitude"] = " "

        qoi_wind = {}
        qoi_wind["ID"] = design
        qoi_wind["Wind farm rating (MW)"] = wind_capacity_mw
        qoi_wind["Number of wind turbines"] = int(num_turbines)
        qoi_wind["Wind turbine rating (MW)"] = turbine_rating_kw*1E-3
        qoi_wind["On/offshore wind"] = greenheart_input["plant_design"][f"scenario{int(design)}"]["wind_location"].capitalize()
        qoi_wind["Turbine foundation"] = foundation_type[design]
        if orbit_input:
            qoi_wind["Distance from shore (km)"] = orbit_input["site"]["distance_to_landfall"]
            qoi_wind["Depth (m)"] = orbit_input["site"]["depth"]
        wind_resource = site.wind_resource
        wind_data = wind_resource.data["data"]
        wind_speed = [W[2] for W in wind_data]
        qoi_wind["Average wind speed (m/s)"] = np.average(wind_speed)

        qoi_pv = {}
        qoi_pv["ID"] = design
        qoi_pv["Solar PV rating (MW)"] = pv_capacity_mw
        solar_resource = site.solar_resource
        qoi_pv["Direct horizontal irradience (kWh/m$^2$)"] = np.average(solar_resource.data["df"])

        qoi_battery = {}
        qoi_battery["ID"] = design
        qoi_battery["Battery power rating (MW)"] = hopp_input["technologies"]["battery"]["system_capacity_kw"]*1E-3
        qoi_battery["Battery energy rating (MWh)"] = hopp_input["technologies"]["battery"]["system_capacity_kwh"]*1E-3
        
        qoi_pem = {}
        qoi_pem["ID"] = design
        qoi_pem["PEM rating (MW)"] = (greenheart_input["electrolyzer"]["rating"])
        qoi_pem["PEM life (hours)"] = (greenheart_input["electrolyzer"]["uptime_hours_until_eol"])
        qoi_pem["PEM EOL efficiency loss ($\%$)"] = (greenheart_input["electrolyzer"]["eol_eff_percent_loss"])
        qoi_pem["PEM turn-down ratio ($\%$)"] = (greenheart_input["electrolyzer"]["turndown_ratio"])*100
        qoi_pem["PEM degradation rate (mV/h)"] = "0.0025"
        qoi_pem["PEM on/off cycle deg. (mv/off-cycle)"] = "0.148"
        qoi_pem["PEM beg.-of-life eff. (kWh/kg)"] = 51.0

        qoi_h2_storage = {}
        qoi_h2_storage["ID"] = design
        qoi_h2_storage["Hydrogen storage type"] = storage_keys[greenheart_input["h2_storage"]["type"]]
        qoi_h2_storage["Hydrogen storage capacity (kt)"] = greenheart_output["h2_storage_capacity_kg"]*1E-6
        qoi_h2_storage["Hydrogen storage max fill rate (t/h)"] = greenheart_output["h2_storage_max_fill_rate_kg_hr"]*1E-3
    
        qoi_steel = {}
        qoi_steel["ID"] = design
        if "steel_capacity" in greenheart_output.keys() and greenheart_output["steel_capacity"] is not None:
            qoi_steel["Steel capacity (Mt/yr)"] = greenheart_output["steel_capacity"]["steel_plant_capacity_mtpy"]*1E-6
        else:
            qoi_steel["Steel capacity (Mt/yr)"] = None
        
        qoi_ammonia = {}
        qoi_ammonia["ID"] = design
        if "ammonia_capacity" in greenheart_output.keys() and greenheart_output["ammonia_capacity"] is not None:
            qoi_ammonia["Ammonia capacity (kt/yr)"] = greenheart_output["ammonia_capacity"]["ammonia_plant_capacity_kgpy"]*1E-6
        else:
            qoi_ammonia["Ammonia capacity (kt/yr)"] = None

        qoi_dictionary_list_general.append(qoi_general)
        qoi_dictionary_list_wind.append(qoi_wind)
        qoi_dictionary_list_pv.append(qoi_pv)
        qoi_dictionary_list_battery.append(qoi_battery)
        qoi_dictionary_list_pem.append(qoi_pem)
        qoi_dictionary_list_h2_storage.append(qoi_h2_storage)
        qoi_dictionary_list_h2_steel.append(qoi_steel)
        qoi_dictionary_list_h2_ammonia.append(qoi_ammonia)
    
    qoi_lists = {"General": qoi_dictionary_list_general,
                 "Wind": qoi_dictionary_list_wind,
                 "PV Solar": qoi_dictionary_list_pv,
                 "Battery": qoi_dictionary_list_battery,
                 "PEM Electrolyzer": qoi_dictionary_list_pem,
                 "Hydrogen Storage": qoi_dictionary_list_h2_storage,
                 "Steel": qoi_dictionary_list_h2_steel,
                 "Ammonia": qoi_dictionary_list_h2_ammonia}
    
    # create dataframes and print latex tables
    i = 0
    general_format = "{:,.1f}".format
    sub_df = pd.DataFrame(qoi_lists["General"])
    sub_df = sub_df.set_index(keys=["ID"], drop=True)
    latex_string = sub_df.fillna(" ").T.to_latex(float_format=general_format)
    lines = latex_string.splitlines()
    header_lines = "\n".join(lines[:4])

    print(header_lines)
    for key in qoi_lists.keys():
        sub_df = pd.DataFrame(qoi_lists[key])
        sub_df = sub_df.set_index(keys=["ID"], drop=True)

        latex_string = sub_df.fillna(" ").T.to_latex(float_format=general_format)
        lines = latex_string.splitlines()
        if i == len(qoi_lists.keys()) - 1:
            print("\\addlinespace[1em]")
            lines = lines[4:] # Remove \begin{tabular} and \toprule
            latex_string_no_env = "\n".join(lines)
        else:
            if i > 0:
                print("\\addlinespace[1em]")
            lines = lines[4:-2] # Remove \begin{tabular} and \end{tabular} together with \toprule and \bottomrule
            latex_string_no_env = "\n".join(lines)

        print("\\textbf{", f"{key}", "} \\\\", sep='')
        print(latex_string_no_env)

        i += 1

    # make short version for executive summary
    es_columns = ["State", "Area", "Product", "On/Offshore", "PEM rating (MW)", 
                  "Wind farm rating (MW)", "Solar PV rating (MW)", "Total generation rating (MW)", 
                  "Battery power rating (MW)", "Battery energy rating (MWh)", "Hydrogen storage capacity (kt)",
                  "Steel capacity (Mt/yr)", "Ammonia capacity (kt/yr)", "LCOH (USD/kg-H$_2$)", 
                  "LCOS (USD/t steel)", "LCOA (USD/kg-NH$_3$)"]
    
    # qoi_es_df = qoi_df[es_columns]

    # print full latex table

    # print executive summary table
    # print(qoi_es_df.fillna(" ").T.to_latex(float_format=general_format))

    return 0

def financial_inputs_table(designs_to_compare=["01", "02", "03", "04", "05"]):
    ref_sys_path = "../reference_systems/"
    plant_files_path = "greenHEART/input-files/plant/"
    output_files_path = "greenHEART/output/data/"

    # get all reference design names
    reference_design_names = os.listdir(ref_sys_path)

    # define region/area
    regions = {"01": "", "02": "", "03": "Gulf Coast", "04": "New York Bight", "05": ""}
    products = {"01": "Steel", "02": "Ammonia", "03": "Hydrogen", "04": "Hydrogen", "05": "Hydrogen"}
    foundation_type = {"01": "", "02": "", "03": "Fixed", "04": "Fixed", "05": "Floating"}
    storage_keys = {"lined_rock_cavern": "Rock cavern", "salt_cavern": "Salt cavern", "none": "None", "pipe": "Underground pipes", "turbine": "In-turbine", "pressure_vessel": "Pressure vessel"}
    states = {"01": "Minnesota", "02": "Texas", "03": "Texas", "04": "New Jersey", "05": "California"}

    qoi_dictionary_list_general = []
    qoi_dictionary_list_wind = []
    qoi_dictionary_list_pv = []
    qoi_dictionary_list_battery = []
    qoi_dictionary_list_h2 = []
    qoi_dictionary_list_steel = []
    qoi_dictionary_list_ammonia = []

    # loop over designs
    for design in designs_to_compare:
        # get full design name
        design_name = [s for s in reference_design_names if design in s][0]
        print(f"Design: {design_name}")
        # load input files
        greenheart_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "greenheart"))
        print("    GreenHEART input loaded")
        hopp_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "hopp"))
        print("    HOPP input loaded")
        gh_financial_parameters = greenheart_input["finance_parameters"]
        print("    Financial input loaded")
        if get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "orbit"):
            orbit_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "orbit"), loader=CombinedLoader)
            print("    ORBIT input loaded")
        else:
            orbit_input = False
            print("    ORBIT input skipped")
        
        ghout_path = get_filename_from_partial_name(ref_sys_path+design_name+"/"+output_files_path, "output.yaml")
        greenheart_output = load_yaml(ghout_path)
        print("    GreenHEART output loaded")

        if "ammonia" in greenheart_input:
            roe_ammonia = greenheart_input["ammonia"]["finances"]["financial_assumptions"]["leverage after tax nominal discount rate"]
            debt_ratio_ammonia = greenheart_input["ammonia"]["finances"]["financial_assumptions"]["debt equity ratio of initial financing"]
            debt_percent_ammonia = debt_ratio_ammonia/(debt_ratio_ammonia + 1.0)
            debt_rate_ammonia = greenheart_input["ammonia"]["finances"]["financial_assumptions"]["debt interest rate"]
        else:
            roe_ammonia = np.nan
            debt_percent_ammonia = np.nan
            debt_rate_ammonia = np.nan

        if "steel" in greenheart_input:
            roe_steel = greenheart_input["steel"]["finances"]["financial_assumptions"]["leverage after tax nominal discount rate"]
            debt_ratio_steel = greenheart_input["steel"]["finances"]["financial_assumptions"]["debt equity ratio of initial financing"]
            debt_percent_steel = debt_ratio_steel/(debt_ratio_steel + 1.0)
            debt_rate_steel = greenheart_input["steel"]["finances"]["financial_assumptions"]["debt interest rate"]
        else:
            roe_steel = np.nan
            debt_percent_steel = np.nan
            debt_rate_steel = np.nan

        # get QOIs
        qoi_general = {}
        qoi_general["ID"] = design
        qoi_general["State"] = states[design]
        qoi_general["Area"] = regions[design]
        qoi_general["Product"] = products[design]
        qoi_general["Foundation"] = foundation_type[design]

        qoi_general["Plant Life (years)"] = greenheart_input["project_parameters"]["project_lifetime"]
        qoi_general["Total income tax rate (\%)"] = gh_financial_parameters["total_income_tax_rate"]*100
        qoi_general["Capital gains tax rate (\%)"] = gh_financial_parameters["capital_gains_tax_rate"]*100
        qoi_general["Property tax rate (\%)"] = gh_financial_parameters["property_tax"]*100
        qoi_general["Property insurance rate (\%)"] = gh_financial_parameters["property_insurance"]*100
        qoi_general["Months working reserve"] = gh_financial_parameters["cash_onhand_months"]
        qoi_general["Debt type"] = "Revolving" #financial_input["financial_parameters"]["debt_type"]
        qoi_general["Depr. method"] = gh_financial_parameters["depreciation_method"]
        qoi_general["Depr. period"] = 7

        # wind
        qoi_wind = {}
        qoi_wind["ID"] = design
        qoi_wind["Real ROE wind (\%)"] = gh_financial_parameters["discount_rate"]["wind"]*100
        qoi_wind["Debt percentage wind (\%)"] = gh_financial_parameters["debt_equity_split"]["wind"]*100
        qoi_wind["Debt interest rate wind (\%)"] = gh_financial_parameters["debt_interest_rate"]["wind"]*100

        # pv
        qoi_pv = {}
        qoi_pv["ID"] = design
        qoi_pv["Real ROE PV (\%)"] = gh_financial_parameters["discount_rate"]["solar"]*100
        qoi_pv["Debt percentage PV (\%)"] = gh_financial_parameters["debt_equity_split"]["solar"]*100
        qoi_pv["Debt interest rate PV (\%)"] = gh_financial_parameters["debt_interest_rate"]["solar"]*100

        # battery
        qoi_batt = {}
        qoi_batt["ID"] = design
        qoi_batt["Real ROE battery (\%)"] = gh_financial_parameters["discount_rate"]["battery"]*100
        qoi_batt["Debt percentage battery (\%)"] = gh_financial_parameters["debt_equity_split"]["battery"]*100
        qoi_batt["Debt interest rate battery (\%)"] = gh_financial_parameters["debt_interest_rate"]["battery"]*100

        # hydrogen
        qoi_h2 = {}
        qoi_h2["ID"] = design
        qoi_h2["Real ROE hydrogen (\%)"] = gh_financial_parameters["discount_rate"]["electrolyzer"]*100
        qoi_h2["Debt percentage hydrogen (\%)"] = gh_financial_parameters["debt_equity_split"]["electrolyzer"]*100
        qoi_h2["Debt interest rate electrolyzer (\%)"] = gh_financial_parameters["debt_interest_rate"]["electrolyzer"]*100
        qoi_h2["Debt interest rate hydrogen storage (\%)"] = gh_financial_parameters["debt_interest_rate"]["h2_storage"]*100
        qoi_h2["WACC-H$_2$ ($\%$)"] = (greenheart_output["profast_sol_lcoh"]["wacc"])*100
        qoi_h2["CRF-H$_2$ ($\%$)"] = greenheart_output["profast_sol_lcoh"]["crf"]*100
        qoi_h2["LCOH (USD/kg-H$_2$)"] = greenheart_output["lcoh"]

        # steel
        qoi_steel = {}
        qoi_steel["ID"] = design
        qoi_steel["Real ROE steel (\%)"] = roe_steel*100
        qoi_steel["Debt percentage steel (\%)"] = debt_percent_steel*100
        if "steel_finance" in greenheart_output.keys() and greenheart_output["steel_finance"] is not None:
            qoi_steel["Debt interest rate steel (\%)"] = debt_rate_steel*100
            qoi_steel["WACC-steel ($\%$)"] = (greenheart_output["steel_finance"]["sol"]["wacc"])*100
        else:
            qoi_steel["WACC-steel ($\%$)"] = None

        if "steel_finance" in greenheart_output.keys() and greenheart_output["steel_finance"] is not None:
            qoi_steel["CRF-steel ($\%$)"] = greenheart_output["steel_finance"]["sol"]["crf"]*100
        else:
            qoi_steel["CRF-steel ($\%$)"] = None

        if "steel_finance" in greenheart_output.keys() and greenheart_output["steel_finance"] is not None:
            qoi_steel["LCOS (USD/t steel)"] = greenheart_output["steel_finance"]["sol"]["price"]
        else:
            qoi_steel["LCOS (USD/t steel)"] = None

        # ammonia
        qoi_ammonia = {}
        qoi_ammonia["ID"] = design
        qoi_ammonia["Real ROE ammonia (\%)"] = roe_ammonia*100
        qoi_ammonia["Debt percentage ammonia (\%)"] = debt_percent_ammonia*100
        qoi_ammonia["Debt interest rate ammonia (\%)"] = debt_rate_ammonia*100

        if "ammonia_finance" in greenheart_output.keys() and greenheart_output["ammonia_finance"] is not None:
            qoi_ammonia["WACC-ammonia ($\%$)"] = (greenheart_output["ammonia_finance"]["sol"]["wacc"])*100
        else:
            qoi_ammonia["WACC-ammonia ($\%$)"] = None

        if "ammonia_finance" in greenheart_output.keys() and greenheart_output["ammonia_finance"] is not None:
            qoi_ammonia["CRF-ammonia ($\%$)"] = greenheart_output["ammonia_finance"]["sol"]["crf"]*100
        else:
            qoi_ammonia["CRF-ammonia ($\%$)"] = None

        if "ammonia_finance" in greenheart_output.keys() and greenheart_output["ammonia_finance"] is not None:
            qoi_ammonia["LCOA (USD/kg-NH$_3$)"] = greenheart_output["ammonia_finance"]["sol"]["price"]
        else:
            qoi_ammonia["LCOA (USD/kg-NH$_3$)"] = None
        
        
        qoi_dictionary_list_general.append(qoi_general)
        qoi_dictionary_list_wind.append(qoi_wind)
        qoi_dictionary_list_pv.append(qoi_pv)
        qoi_dictionary_list_battery.append(qoi_batt)
        qoi_dictionary_list_h2.append(qoi_h2)
        qoi_dictionary_list_steel.append(qoi_steel)
        qoi_dictionary_list_ammonia.append(qoi_ammonia)
    
        qoi_lists = {"General": qoi_dictionary_list_general,
                 "Wind": qoi_dictionary_list_wind,
                 "PV Solar": qoi_dictionary_list_pv,
                 "Battery": qoi_dictionary_list_battery,
                 "Hydrogen": qoi_dictionary_list_h2,
                 "Steel": qoi_dictionary_list_steel,
                 "Ammonia": qoi_dictionary_list_ammonia}
    
    # create dataframes and print latex tables
    i = 0
    general_format = "{:,.1f}".format
    sub_df = pd.DataFrame(qoi_lists["General"])
    sub_df = sub_df.set_index(keys=["ID"], drop=True)
    latex_string = sub_df.fillna(" ").T.to_latex(float_format=general_format)
    lines = latex_string.splitlines()
    header_lines = "\n".join(lines[:4])

    print(header_lines)
    for key in qoi_lists.keys():
        sub_df = pd.DataFrame(qoi_lists[key])
        sub_df = sub_df.set_index(keys=["ID"], drop=True)

        latex_string = sub_df.fillna(" ").T.to_latex(float_format=general_format)
        lines = latex_string.splitlines()
        if i == len(qoi_lists.keys()) - 1:
            print("\\addlinespace[1em]")
            lines = lines[4:] # Remove \begin{tabular} and \toprule
            latex_string_no_env = "\n".join(lines)
        else:
            if i > 0:
                print("\\addlinespace[1em]")
            lines = lines[4:-2] # Remove \begin{tabular} and \end{tabular} together with \toprule and \bottomrule
            latex_string_no_env = "\n".join(lines)

        print("\\textbf{", f"{key}", "} \\\\", sep='')
        print(latex_string_no_env)

        i += 1

def costs_table(designs_to_compare=["01", "02", "03", "04", "05"]):
    ref_sys_path = "../reference_systems/"
    plant_files_path = "greenHEART/input-files/plant/"
    output_files_path = "greenHEART/output/data/"

    # get all reference design names
    reference_design_names = os.listdir(ref_sys_path)

    # define region/area
    regions = {"01": "", "02": "", "03": "Gulf Coast", "04": "New York Bight", "05": ""}
    products = {"01": "Steel", "02": "Ammonia", "03": "Hydrogen", "04": "Hydrogen", "05": "Hydrogen"}
    states = {"01": "Minnesota", "02": "Texas", "03": "Texas", "04": "New Jersey", "05": "California"}

    qoi_dictionary_list_general = []
    qoi_dictionary_list_wind = []
    qoi_dictionary_list_pv = []
    qoi_dictionary_list_battery = []
    qoi_dictionary_list_pem = []
    qoi_dictionary_list_h2_storage = []
    qoi_dictionary_list_steel = []
    qoi_dictionary_list_ammonia = []

    # loop over designs
    for design in designs_to_compare:
        # get full design name
        design_name = [s for s in reference_design_names if design in s][0]
        print(f"Design: {design_name}")
        # load input files
        greenheart_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "greenheart"))
        print("    GreenHEART input loaded")
        hopp_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "hopp"))
        print("    HOPP input loaded")
        ghout_path = get_filename_from_partial_name(ref_sys_path+design_name+"/"+output_files_path, "output.yaml")
        greenheart_output = load_yaml(ghout_path)
        print("GreenHEART output loaded")

        if get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "orbit"):
            orbit_input = load_yaml(get_filename_from_partial_name(ref_sys_path+design_name+"/"+plant_files_path, "orbit"), loader=CombinedLoader)
            print("    ORBIT input loaded")
        else:
            orbit_input = False
            print("    ORBIT input skipped")

        if "ammonia" in greenheart_input:
            ammonia_capex = str(np.round(greenheart_output["ammonia_costs"]["capex_total"]/greenheart_output["ammonia_capacity"]["ammonia_plant_capacity_kgpy"]*1E3, decimals=1))+"$^*$"
            ammonia_opex = str(np.round(greenheart_output["ammonia_costs"]["total_fixed_operating_cost"]/greenheart_output["ammonia_capacity"]["ammonia_plant_capacity_kgpy"]*1E3, decimals=1))+"$^*$"
        else:
            ammonia_capex = np.nan
            ammonia_opex = np.nan

        if "steel" in greenheart_input:
            steel_capex = str(np.round(greenheart_output["steel_costs"]["total_plant_cost"]/greenheart_output["steel_capacity"]["steel_plant_capacity_mtpy"], decimals=2))+"$^*$"
            steel_opex = str(np.round(greenheart_output["steel_costs"]["total_fixed_operating_cost"]/greenheart_output["steel_capacity"]["steel_plant_capacity_mtpy"], decimals=1))+"$^*$"
        else:
            steel_capex = np.nan
            steel_opex = np.nan

        nturbines = hopp_input["technologies"]["wind"]["num_turbines"]
        turbine_rating = hopp_input["technologies"]["wind"]["turbine_rating_kw"]
        if "wind_installed_cost_mw" in hopp_input["config"]["cost_info"]:
            wind_installed_cost_kw = np.round(hopp_input["config"]["cost_info"]["wind_installed_cost_mw"]*1E-3, decimals=1)
        else:
            wind_installed_cost_kw = str(np.round(greenheart_output["capex_breakdown"]["wind"]/(nturbines*turbine_rating), decimals=1))+"$^*$"

        if "wind_om_per_kw" in hopp_input["config"]["cost_info"]:
            wind_om_per_kw = np.round(hopp_input["config"]["cost_info"]["wind_om_per_kw"], decimals=2)
        else:
            wind_om_per_kw = str(np.round(greenheart_output["opex_breakdown_annual"]["wind_and_electrical"]/(nturbines*turbine_rating), decimals=1))+"$^*$"

        # get QOIs
        qoi_general = {}
        qoi_general["ID"] = design
        qoi_general["State"] = states[design]
        qoi_general["Area"] = regions[design]
        qoi_general["Product"] = products[design]

        qoi_wind = {}
        qoi_wind["ID"] = design
        qoi_wind["Wind CapEx (USD/kW)"] = wind_installed_cost_kw
        qoi_wind["Wind fixed O\&M (USD/kW)"] = wind_om_per_kw

        qoi_pv = {}
        qoi_pv["ID"] = design
        qoi_pv["Solar PV  CapEx (USD/kW)"] = hopp_input["config"]["cost_info"]["solar_installed_cost_mw"]*1E-3
        qoi_pv["Solar PV fixed O\&M (USD/kW)"] = hopp_input["config"]["cost_info"]["pv_om_per_kw"]

        qoi_batt = {}
        qoi_batt["ID"] = design
        qoi_batt["Battery CapEx (USD/kW)"] = hopp_input["config"]["cost_info"]["storage_installed_cost_mw"]*1E-3
        qoi_batt["Battery CapEx (USD/kWh)"] = hopp_input["config"]["cost_info"]["storage_installed_cost_mwh"]*1E-3
        qoi_batt["Battery fixed O\&M (USD/kW)"] = hopp_input["config"]["cost_info"]["battery_om_per_kw"]

        qoi_pem = {}
        qoi_pem["ID"] = design
        qoi_pem["PEM CapEx 1 MW system (USD/kW)"] = greenheart_input["electrolyzer"]["electrolyzer_capex"]
        qoi_pem["PEM stack replacement cost ($\%$ of CapEx)"] = (greenheart_input["electrolyzer"]["replacement_cost_percent"])*100
        qoi_pem["PEM fixed O\&M (USD/kW)"] = str(np.round(greenheart_output["opex_breakdown_annual"]["electrolyzer"]/(greenheart_input["electrolyzer"]["rating"]*1E3), decimals=1))+"$^*$"
        qoi_pem["PEM variable O\&M (USD/MW)"] = greenheart_input["electrolyzer"]["var_om"]*1E3

        qoi_h2_storage= {}
        qoi_h2_storage["ID"] = design
        qoi_h2_storage["H$_2$ Storage CapEx (USD/kg)"] = str(np.round(greenheart_output["capex_breakdown"]["h2_storage"]/(greenheart_output["h2_storage_capacity_kg"]), decimals=1)) + "$^*$"
        qoi_h2_storage["H$_2$ Storage fixed O\&M (USD/t)"] = str(np.round(greenheart_output["opex_breakdown_annual"]["h2_storage"]/(greenheart_output["h2_storage_capacity_kg"]*1E-3), decimals=1)) + "$^*$"

        qoi_steel = {}
        qoi_steel["ID"] = design
        qoi_steel["Steel plant CapEx (USD/Mt)"] = steel_capex
        qoi_steel["Steel plant fixed O\&M (USD/Mt)"] = steel_opex

        qoi_ammonia = {}
        qoi_ammonia["ID"] = design
        qoi_ammonia["Ammonia plant CapEx (USD/t)"] = ammonia_capex
        qoi_ammonia["Ammonia plant fixed O\&M (USD/t)"] = ammonia_opex


        qoi_dictionary_list_general.append(qoi_general)
        qoi_dictionary_list_wind.append(qoi_wind)
        qoi_dictionary_list_pv.append(qoi_pv)
        qoi_dictionary_list_battery.append(qoi_batt)
        qoi_dictionary_list_pem.append(qoi_pem)
        qoi_dictionary_list_h2_storage.append(qoi_h2_storage)
        qoi_dictionary_list_steel.append(qoi_steel)
        qoi_dictionary_list_ammonia.append(qoi_ammonia)
    
    qoi_lists = {"General": qoi_dictionary_list_general,
                 "Wind": qoi_dictionary_list_wind,
                 "PV Solar": qoi_dictionary_list_pv,
                 "Battery": qoi_dictionary_list_battery,
                 "PEM Electrolyzer": qoi_dictionary_list_pem,
                 "Hydrogen Storage": qoi_dictionary_list_h2_storage,
                 "Steel": qoi_dictionary_list_steel,
                 "Ammonia": qoi_dictionary_list_ammonia}
    
    # create dataframes and print latex tables
    i = 0
    general_format = "{:,.1f}".format
    sub_df = pd.DataFrame(qoi_lists["General"])
    sub_df = sub_df.set_index(keys=["ID"], drop=True)
    latex_string = sub_df.fillna(" ").T.to_latex(float_format=general_format)
    lines = latex_string.splitlines()
    header_lines = "\n".join(lines[:4])

    print(header_lines)
    for key in qoi_lists.keys():
        sub_df = pd.DataFrame(qoi_lists[key])
        sub_df = sub_df.set_index(keys=["ID"], drop=True)

        latex_string = sub_df.fillna(" ").T.to_latex(float_format=general_format)
        lines = latex_string.splitlines()
        if i == len(qoi_lists.keys()) - 1:
            print("\\addlinespace[1em]")
            lines = lines[4:] # Remove \begin{tabular} and \toprule
            latex_string_no_env = "\n".join(lines)
        else:
            if i > 0:
                print("\\addlinespace[1em]")
            lines = lines[4:-2] # Remove \begin{tabular} and \end{tabular} together with \toprule and \bottomrule
            latex_string_no_env = "\n".join(lines)

        print("\\textbf{", f"{key}", "} \\\\", sep='')
        print(latex_string_no_env)

        i += 1

if __name__ == "__main__":

    # comparison_table()
    # financial_inputs_table()
    costs_table()